name = str(input("Enter a name: "))
age = int(input("Enter your age: " ))
price = float(input("Enter the price: " ))
is_student = bool(int(input("Are you a student? (1 for Yes, 0 for No): " )))
print(type(name))
print(type(age))
print(type(price))
print(type(is_student))
print(f"your name is: {name}, your age is: {age}, the price is: {price}, student status: {is_student}")
